(+) draw holes and render transparent mesh
structureio/StructureKit pull request #4
Opened 2024-12-16 07:13 UTC by kazi-mifta

- add STKPoint3D for receiving hole vertices
- modified depth stencil function for transparent solid mode
- added transparent solid mesh rendering style
- added variables to render lines. Lines are rendered using the thick line renderer.

2024-12-19 15:11 UTC, makiavell requested changes

2024-12-19 15:14 UTC, a-tokar approved these changes

2024-12-19 20:51 UTC, kazi-mifta commented on Sources/StructureKit/Metal/STKMeshRenderers.swift
> +    }
Move `transparent: Bool = false` from the constructor to render() function. Renamed transparent to `hideBackFaces`.

2025-01-09 18:11 UTC, makiavell approved these changes

2025-01-10 09:50 UTC, merged